word = "hola"
print("Word: "+word)
print(word[1:3])
print(word[::2])
print(word[::-1])
print(word[::-2])
print(len(word))
print(word)
print(word.islower())
print(word.upper())
print(word.isupper())
print(word.upper().isupper())
word = "Hola"
print(word)
print(word.isupper())
print(word.lower())
print(word.islower())
print(word.find("la"))
print(word.find("la",1))
print(word.find("la",3))
print(word.find("pl"))
print(word.isdigit())
print(word.endswith("a"))
print(word.endswith("o", 0, 2))
print(word.startswith("h"))
print(word.startswith("H"))
words = "Hola amigos, cómo están?"
print(words.split())
print(words.split(" ", 2))
print(" ".split("a"))
myTuple = ("John", "Peter", "Vicky")
x = " ".join(myTuple)
print(x)
